### PR TITLE
test, do not merge

### PR DESCRIPTION
**Pull request by wattli**
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by wattli** [comment]
@ldemailly , i am testing whether the release-0.2 branch has pre-submit.sh okay

**Comment by wattli** [comment]
You don't have to review, just want to see if pre-submit can pass.

**Comment by wattli** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_auth/303/auth-presubmit/300/

The pre-submit does not work. I will fix it.

**Comment by ldemailly** [comment]
that's why I had added seb's commit to my PR

**Pull request closed without merging**
